base: 'https://samariter.ddev.site/home'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: de
    languageId: 0
rootPageId: 2
websiteTitle: Samariterbund
